//cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

//orders
export const ADD_ORDER = 'ADD_ORDER';

//products
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_PRODUCTS_ERROR_MESSAGE = 'SET_PRODUCTS_ERROR_MESSAGE';
export const RESET_PRODUCTS_ERROR_MESSAGE = 'RESET_PRODUCTS_ERROR_MESSAGE';
