//auth
export const AUTHENTICATE = 'AUTHENTICATE';
export const LOGOUT = '';
export const SET_DID_TRY_AL = 'SET_DID_TRY_AL';
export const SET_AUTH_ERROR_MESSAGE = 'SET_AUTH_ERROR_MESSAGE';
export const RESET_AUTH_ERROR_MESSAGE = 'RESET_AUTH_ERROR_MESSAGE';

//cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

//orders
export const SET_ORDERS = 'SET_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const SET_ORDERS_ERROR_MESSAGE = 'SET_ORDERS_ERROR_MESSAGE';
export const RESET_ORDERS_ERROR_MESSAGE = 'RESET_ORDERS_ERROR_MESSAGE';

//products
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const SET_PRODUCTS_ERROR_MESSAGE = 'SET_PRODUCTS_ERROR_MESSAGE';
export const RESET_PRODUCTS_ERROR_MESSAGE = 'RESET_PRODUCTS_ERROR_MESSAGE';
export const SET_ADMIN_ERROR_MESSAGE = 'SET_ADMIN_ERROR_MESSAGE';
export const RESET_ADMIN_ERROR_MESSAGE = 'RESET_ADMIN_ERROR_MESSAGE';
